// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8FZ15YswhIPclNTdP1rI2Vab8HVuHXYc',
    appId: '1:169250585311:web:a02f9608d9165b59b3476a',
    messagingSenderId: '169250585311',
    projectId: 'listify-ed5d0',
    authDomain: 'listify-ed5d0.firebaseapp.com',
    storageBucket: 'listify-ed5d0.firebasestorage.app',
    measurementId: 'G-JMJ3JWW5Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPMSVJwTqeghfavWtA7RDrVHgHe1kRe0',
    appId: '1:169250585311:android:3aa96ef2923f6851b3476a',
    messagingSenderId: '169250585311',
    projectId: 'listify-ed5d0',
    storageBucket: 'listify-ed5d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ84419ruWihccaGawYYhlHXF2r3G83x8',
    appId: '1:169250585311:ios:1b3c2d2137a6ebabb3476a',
    messagingSenderId: '169250585311',
    projectId: 'listify-ed5d0',
    storageBucket: 'listify-ed5d0.firebasestorage.app',
    iosBundleId: 'com.gokmen.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ84419ruWihccaGawYYhlHXF2r3G83x8',
    appId: '1:169250585311:ios:2aa0e71b7a97fc7db3476a',
    messagingSenderId: '169250585311',
    projectId: 'listify-ed5d0',
    storageBucket: 'listify-ed5d0.firebasestorage.app',
    iosBundleId: 'com.example.listifyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8FZ15YswhIPclNTdP1rI2Vab8HVuHXYc',
    appId: '1:169250585311:web:1427960591cee7afb3476a',
    messagingSenderId: '169250585311',
    projectId: 'listify-ed5d0',
    authDomain: 'listify-ed5d0.firebaseapp.com',
    storageBucket: 'listify-ed5d0.firebasestorage.app',
    measurementId: 'G-2VVNYF6EF4',
  );
}
